### ISSUE TITLE
Create / submit paper problem

### ISSUE THREAD

**Issue by kmader** [openjournals/jose-old#13]
I tried to create a new submission on the JOSE site but something with the ORCID credentials did not work.

![image](https://user-images.githubusercontent.com/116120/42732909-090c0aa8-882a-11e8-9b4d-2b93c76ce106.png)

**Comment by willingc** [comment]
Thanks for the report @kmader and sorry for the inconvenience.

I'm confirming that I see the same behavior when I click "Submit" on the navbar (whether or not I am already signed into ORCID.

**Comment by kmader** [comment]
It seems to work for me now and so I made a submission but not sure where the problem came from.

**Comment by willingc** [comment]
Hmm...let's keep this open for a bit. I definitely had the same issue when trying to do through hotel wifi. Will try in the Jupyter Lab later today to see if it was perhaps a networking thing.

Any difference in your location when you tried @kmader?

Glad you got it working 👍

**Comment by kmader** [comment]
@willingc unfortunately, it was a bad experiment a difference in location and browser session. I was already logged into ORCID when I tried again and so maybe it is being logged out combined with clicking submit?

**Comment by gregcaporaso** [comment]
I'm getting this same error when I try to log in to submit an manuscript, and I haven't been able to work around it yet. Any suggestions? Thanks in advance for the help with this!

**Comment by labarba** [comment]
@gregcaporaso I found mention of this issue here: https://members.orcid.org/api/resources/troubleshooting

I don't know enough to make a meaty suggestion. All I can think of is log out of ORCID and try again, try another browser, or clear cache. Obvious things. For something technical that could be done on our side, we'll have to wait until @arfon comes back from vacay to ask him.

**Comment by arfon** [comment]
I *think* this is because I didn't have `https://jose.theoj.org`listed as one of the JOSE URLs (I only had the non-https version `http://jose.theoj.org`).

I've now added `https://jose.theoj.org` as one of the callback URLs for my ORCID developer account and so this shouldn't happen again.

@gregcaporaso - could you try again now please?

**Comment by gregcaporaso** [comment]
@arfon, that worked for me. Thanks for the fix!

**Comment by moorepants** [comment]
Closing, please reopen if it arises again.
